[build]
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

[functions."reflect"]
  timeout = 26

[functions."chat"]
  timeout = 26

[functions."archive"]
  timeout = 26

[functions."scheduler"]
  schedule = "0 0,12 * * *"

[functions."repository"]
  timeout = 26
